# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 033d272b127d42a39abda56abcff8bd477e8ada85117612f57705d09fbc6146c690e23dfb172cf5a215dcac58a5f46ef400e8789772100356885586459892421

test:
  secret_key_base: b23855ae26e4e78fe7abcdd23ff6aae1cfa82e7ce11824c9e710a1bcf7f4075298e3b4e743d452b505770ee529a5befe5f77de090eece7988332759638eff0cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
